import DataBase.BaseDatos as bd
import DataBase.BdRow as bdRow


valor:bdRow.BdRow= bd.bdSearch('aba',1)
print(type(valor.byte))
print('bytes: ' + str(valor.byte))
print('---------------------')
print(type(valor.ciclo))
print('ciclos: ' + str(valor.ciclo))
print('---------------------')
print(type(valor.id))
print('Id: ' +str(valor.id))
print('---------------------')
print(type(valor.mod))
print('Modo: ' +str(valor.mod))
print('---------------------')
print(type(valor.no))
print('No. ' + str(valor.no))
print('---------------------')
print(type(valor.opcode))
print('Opcode ' +valor.opcode)
print('---------------------')
print(type(valor.mnemonico))
print('Mnemonico ' +valor.mnemonico)
print(valor)